graphql:
  servlet:
    # Sets if GraphQL servlet should be created and exposed. If not specified defaults to "true".
    enabled: true
    # Sets the path where GraphQL servlet will be exposed. If not specified defaults to "/graphql"
    mapping: /graphql/as
    cors-enabled: true
    cors:
      allowed-origins: http://some.domain.com
      allowed-methods: GET, HEAD, POST
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    # Sets if asynchronous operations are supported for GraphQL requests. If not specified defaults to true.
    async-mode-enabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql/as
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: latest
  props:
    resources:
      query: query.graphql.as
      defaultQuery: defaultQuery.graphql.as
      variables: variables.graphql.as
    variables:
      editorTheme: "solarized light"
  headers:
    Authorization: "Bearer <your-token>"