auth:
  - name: "logintokenheader"
    loginEndpointAuth:
      endpoint: "/api/logintokenheader/login"
      verb: POST
      headers:
        - name: "Authorization"
          value: "foo 123"
      token:
        extractFrom: "body"
        extractSelector: "/token/authToken"
        sendIn: "header"
        sendName: "Authorization"
        sendTemplate: "Bearer {token}"
