[[auth]]
name="logintoken"
[auth.loginEndpointAuth]
endpoint="/api/logintoken/login"
payloadRaw= """
{"userId": "foo", "password":"123"}
"""
verb="POST"
contentType="application/json"
[auth.loginEndpointAuth.token]
sendTemplate="Bearer {token}"
extractSelector = "/token/authToken"
extractFrom="body"
sendName="Authorization"
sendIn="header"
